export const PRODUCTS_ACTION_TYPES = {
    // ADD_PRODUCTS: 'products/ADD_PRODUCTS',
    SET_PRODUCTS_START: 'products/SET_PRODUCTS_START',
    SET_PRODUCTS_SUCCESS: 'products/SET_PRODUCTS_SUCCESS',
    SET_PRODUCTS_FAILED: 'products/SET_PRODUCTS_FAILED',
}